# Autogenerated wrapper script for LibreDWG_jll for aarch64-linux-gnu
export dwg2dxf, dwg2svg, dwgbmp, dwglayers, dwgread, dwgrewrite, dwgwrite, dxf2dwg, dxfwrite, libredwg

using Libiconv_jll
JLLWrappers.@generate_wrapper_header("LibreDWG")
JLLWrappers.@declare_library_product(libredwg, "libredwg.so.0")
JLLWrappers.@declare_executable_product(dwg2dxf)
JLLWrappers.@declare_executable_product(dwg2svg)
JLLWrappers.@declare_executable_product(dwgbmp)
JLLWrappers.@declare_executable_product(dwglayers)
JLLWrappers.@declare_executable_product(dwgread)
JLLWrappers.@declare_executable_product(dwgrewrite)
JLLWrappers.@declare_executable_product(dwgwrite)
JLLWrappers.@declare_executable_product(dxf2dwg)
JLLWrappers.@declare_executable_product(dxfwrite)
function __init__()
    JLLWrappers.@generate_init_header(Libiconv_jll)
    JLLWrappers.@init_library_product(
        libredwg,
        "lib/libredwg.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_executable_product(
        dwg2dxf,
        "bin/dwg2dxf",
    )

    JLLWrappers.@init_executable_product(
        dwg2svg,
        "bin/dwg2SVG",
    )

    JLLWrappers.@init_executable_product(
        dwgbmp,
        "bin/dwgbmp",
    )

    JLLWrappers.@init_executable_product(
        dwglayers,
        "bin/dwglayers",
    )

    JLLWrappers.@init_executable_product(
        dwgread,
        "bin/dwgread",
    )

    JLLWrappers.@init_executable_product(
        dwgrewrite,
        "bin/dwgrewrite",
    )

    JLLWrappers.@init_executable_product(
        dwgwrite,
        "bin/dwgwrite",
    )

    JLLWrappers.@init_executable_product(
        dxf2dwg,
        "bin/dxf2dwg",
    )

    JLLWrappers.@init_executable_product(
        dxfwrite,
        "bin/dxfwrite",
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
