# Autogenerated wrapper script for LibreDWG_jll for i686-w64-mingw32
export dwg2dxf, dwg2svg, dwgbmp, dwglayers, dwgread, dwgrewrite, dwgwrite, dxf2dwg, dxfwrite, libredwg

using Libiconv_jll
JLLWrappers.@generate_wrapper_header("LibreDWG")
JLLWrappers.@declare_library_product(libredwg, "libredwg-0.dll")
JLLWrappers.@declare_executable_product(dwg2dxf)
JLLWrappers.@declare_executable_product(dwg2svg)
JLLWrappers.@declare_executable_product(dwgbmp)
JLLWrappers.@declare_executable_product(dwglayers)
JLLWrappers.@declare_executable_product(dwgread)
JLLWrappers.@declare_executable_product(dwgrewrite)
JLLWrappers.@declare_executable_product(dwgwrite)
JLLWrappers.@declare_executable_product(dxf2dwg)
JLLWrappers.@declare_executable_product(dxfwrite)
function __init__()
    JLLWrappers.@generate_init_header(Libiconv_jll)
    JLLWrappers.@init_library_product(
        libredwg,
        "bin\\libredwg-0.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_executable_product(
        dwg2dxf,
        "bin\\dwg2dxf.exe",
    )

    JLLWrappers.@init_executable_product(
        dwg2svg,
        "bin\\dwg2SVG.exe",
    )

    JLLWrappers.@init_executable_product(
        dwgbmp,
        "bin\\dwgbmp.exe",
    )

    JLLWrappers.@init_executable_product(
        dwglayers,
        "bin\\dwglayers.exe",
    )

    JLLWrappers.@init_executable_product(
        dwgread,
        "bin\\dwgread.exe",
    )

    JLLWrappers.@init_executable_product(
        dwgrewrite,
        "bin\\dwgrewrite.exe",
    )

    JLLWrappers.@init_executable_product(
        dwgwrite,
        "bin\\dwgwrite.exe",
    )

    JLLWrappers.@init_executable_product(
        dxf2dwg,
        "bin\\dxf2dwg.exe",
    )

    JLLWrappers.@init_executable_product(
        dxfwrite,
        "bin\\dxfwrite.exe",
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
